urls.py
# accounts/urls.py
from django.urls import path

from . import views
from . import views_stripe
from . import views_paypal
app_name = 'payment'
urlpatterns = [
    path('success', views.payment_success, name='success'),
    path('cancel', views.payment_cancel, name='cancel'),
    path('select-gateway', views.select_gateway, name='select_gateway'),

    # ----- Paypal ----------
    path('paypal/checkout', views_paypal.checkout, name='paypal_checkout'),

    # ----- Stripe ----------
    path('stripe/checkout', views_stripe.checkout, name='stripe_checkout'),
]

models.py
from django.db import models

# Create your models here.
from django.contrib.auth import get_user_model

PAYMENT_STATUS = (
    ('initiated', 'Initiated'),
    ('success', 'Success'),
    ('failed', 'failed'),
    ('cancelled', 'cancelled')
)


class Transaction(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name="payment_transaction")
    plan = models.PositiveIntegerField()
    currency = models.CharField(max_length=5, null=True, blank=True)
    amount = models.FloatField(null=True, blank=True)
    payment_gateway = models.CharField(max_length=100, null=True, blank=True)
    status = models.CharField(max_length=30, choices=PAYMENT_STATUS, null=True, blank=True)

    def __str__(self):
        return "{} - {}({}) {} - {}".format(self.user, self.amount, self.currency, self.payment_gateway, self.status)

views.py
from django.shortcuts import render

# Create your views here.
from . import settings
from django.http import JsonResponse
from django.utils.translation import gettext_lazy as _

from django.contrib.auth.decorators import login_required
from .utils import update_transaction
from .models import PAYMENT_STATUS


@login_required
def select_gateway(request):
    plan = request.GET.get('plan')
    return render(request, 'payment/select_gateway.html', {'plan': plan})


@login_required
def payment_success(request):
    update_transaction(request, status=PAYMENT_STATUS[1][0])
    return render(request, '{}/success.html'.format(settings.APP_NAME))


@login_required
def payment_cancel(request):
    update_transaction(request, status=PAYMENT_STATUS[3][0])
    return render(request, '{}/cancel.html'.format(settings.APP_NAME))

templates/payment/base.html
{% load static %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <meta name="description" content="">
    <meta name="author" content="">

    <title>
    {% block title %}

    {% endblock title %}
  </title>
  <link rel="shortcut icon" href="{% static 'webster/images/favicon.ico' %}" />

<!-- font -->
<link  rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:300,300i,400,500,500i,600,700,800,900|Poppins:200,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Dosis:300,400,500,600,700,800">

<!-- Plugins -->
<link rel="stylesheet" type="text/css" href="{% static 'webster/css/plugins-css.css' %}" />

<!-- revoluation -->
<link rel="stylesheet" type="text/css" href="{% static 'webster/revolution/css/settings.css' %}" media="screen" />

<!-- Typography -->
<link rel="stylesheet" type="text/css" href="{% static 'webster/css/typography.css' %}" />

<!-- Shortcodes -->
<link rel="stylesheet" type="text/css" href="{% static 'webster/css/shortcodes/shortcodes.css' %}" />

<!-- Style -->
<link rel="stylesheet" type="text/css" href="{% static 'webster/css/style.css' %}" />

<!-- Responsive -->
<link rel="stylesheet" type="text/css" href="{% static 'webster/css/responsive.css' %}" />

     <style>
    .nav-item{
         width:32.9%;
         background-color: white;
    }
    .nav-link-a {
        font-size: 12px;
        padding: 0px;
    }
    .nav-link active{
        background-color: white;
    }
    .hide{
        display: none;
    }
</style>
</head>
    <body>
        <input type="hidden" name="csrf_token" id="csrf_token" class="csrf_token" value="{{csrf_token}}">
<div class="wrapper">

<!--=================================
 preloader -->


</div>

<header id="header" class="header light">
  <!--<div class="topbar">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 col-md-6 xs-mb-10">
        <div class="topbar-call text-center text-md-left">
          <ul>
            <li><i class="fa fa-envelope-o theme-color"></i> gethelp@yogachar.com</li>
             <li><i class="fa fa-phone"></i> <a href="tel:+7042791249"> <span>+(704) 279-1249 </span> </a> </li>
          </ul>
        </div>
      </div>
      <div class="col-lg-6 col-md-6">
        <div class="topbar-social text-center text-md-right">
          <ul>
            <li><a href="#"><span class="ti-facebook"></span></a></li>
            <li><a href="#"><span class="ti-instagram"></span></a></li>
            <li><a href="#"><span class="ti-google"></span></a></li>
            <li><a href="#"><span class="ti-twitter"></span></a></li>
            <li><a href="#"><span class="ti-linkedin"></span></a></li>
            <li><a href="#"><span class="ti-dribbble"></span></a></li>
          </ul>
        </div>
      </div>
     </div>
  </div>
</div>
-->
<!--=================================
 mega menu -->

<div class="menu">
  <!-- menu start -->
   <nav id="menu" class="mega-menu bg-overlay-black-90">
    <!-- menu list items container -->
    <section class="menu-list-items">
     <div class="container">
      <div class="row">
       <div class="col-lg-12 col-md-12">
        <!-- menu logo -->
        <ul class="menu-logo">
            <li>
                <a href="/"><h1 class="theme-color"><b>{{request.domain}} </b></h1> </a>
            </li>
        </ul>
        <!-- menu links -->
        <div class="menu-bar">
            <!--<ul class="menu-links pull-lefr">

                <li><a href="javascript:void(0)">Home <i class="fa fa-angle-down fa-indicator"></i></a>
                    &lt;!&ndash; drop down full width &ndash;&gt;
                    <div class="drop-down grid-col-12">
                        &lt;!&ndash;grid row&ndash;&gt;
                        <div class="grid-row">
                            &lt;!&ndash;grid column 3&ndash;&gt;
                            <div class="grid-col-3">
                                <ul>
                                    <li><a href="index-01.html">yogachar default <span class="badge badge-primary">Default</span>
                                    </a></li>
                                    <li><a href="index-02.html">Classic Business </a></li>


                                </ul>
                            </div>

                        </div>
                    </div>
                </li>
            </ul>-->

        </div>
       </div>
      </div>
     </div>
    </section>
   </nav>
  <!-- menu end -->
 </div>
</header>

{% block content %}{% endblock %}

{% include 'accounts/_footer.html' %}

<div id="back-to-top"><a class="top arrow" href="#top"><i class="fa fa-angle-up"></i> <span>TOP</span></a></div>

<!--=================================
 jquery -->

<!-- jquery -->
<script src="{% static 'webster/js/jquery-3.4.1.min.js' %}"></script>

<!-- plugins-jquery -->
<script src="{% static 'webster/js/plugins-jquery.js' %}"></script>

<!-- plugin_path -->
<script>var plugin_path = '{% static 'webster/' %}js/';</script>

<!-- REVOLUTION JS FILES -->
<script src="{% static 'webster/revolution/js/jquery.themepunch.tools.min.js' %}"></script>
<script src="{% static 'webster/revolution/js/jquery.themepunch.revolution.min.js' %}"></script>

<!-- SLIDER REVOLUTION 5.0 EXTENSIONS  (Load Extensions only on Local File Systems !  The following part can be removed on Server for On Demand Loading) -->
<script src="{% static 'webster/revolution/js/extensions/revolution.extension.actions.min.js' %}"></script>
<script src="{% static 'webster/revolution/js/extensions/revolution.extension.carousel.min.js' %}"></script>
<script src="{% static 'webster/revolution/js/extensions/revolution.extension.kenburn.min.js' %}"></script>
<script src="{% static 'webster/revolution/js/extensions/revolution.extension.layeranimation.min.js' %}"></script>
<script src="{% static 'webster/revolution/js/extensions/revolution.extension.migration.min.js' %}"></script>
<script src="{% static 'webster/revolution/js/extensions/revolution.extension.navigation.min.js' %}"></script>
<script src="{% static 'webster/revolution/js/extensions/revolution.extension.parallax.min.js' %}"></script>
<script src="{% static 'webster/revolution/js/extensions/revolution.extension.slideanims.min.js' %}"></script>
<script src="{% static 'webster/revolution/js/extensions/revolution.extension.video.min.js' %}"></script>
<!-- revolution custom -->
<script src="{% static 'webster/revolution/js/revolution-custom.js' %}"></script>

<!-- custom -->
<script src="{% static 'webster/js/custom.js' %}"></script>

{% block scripts %}{% endblock %}
    </body>
</html>

templates/payment/cancel.html
{% extends 'payment/base.html' %}
{% load static %}
{% block content %}
<section class="page-section-ptb login-signup parallax"
         style="background: url();">
    <div class="container">
            <div class="row mt-70">
                <div class="col-lg-12 col-md-12 mx-auto text-center">
                    <h4 class="mb-30 ">Payment Cancelled</h4>
                </div>
            </div>

    </div>
</section>

{% endblock %}

templates/payment/paypal/checkout.html
{% extends 'payment/base.html' %}
{% load static %}
{% block content %}
<script
    src="https://www.paypal.com/sdk/js?client-id={{paypal_client_id}}"> // Required. Replace SB_CLIENT_ID with your sandbox client ID.
  </script>
<section class="page-section-ptb login-signup parallax" >
    <div class="container">
            <div class="row mt-70">
                <div class="col-lg-12 col-md-12 mx-auto text-center">
                    <h4 class="mb-30 ">Checkout : {{currency}} {{price}}</h4>
                </div>
                <div class="col-lg-12 col-md-12">
                    <div class="row">
                            <div id="paypal-button-container" class="mx-auto"></div>
                    </div>
                </div>

            </div>

    </div>
</section>

{% endblock %}
{% block scripts %}
<script>
    paypal.Buttons({
    createOrder: function(data, actions) {
      // This function sets up the details of the transaction, including the amount and line item details.
      return actions.order.create({
        purchase_units: [{
          amount: {
            value: '{{price}}',
            currencyCode: '{{currency}}'
          }
        }]
      });
    },
    onApprove: function(data, actions) {
      // This function captures the funds from the transaction.
      return actions.order.capture().then(function(details) {
        // This function shows a transaction success message to your buyer.
            window.location = "{{success_url}}";
      });
    }
  }).render('#paypal-button-container');
  </script>
{% endblock %}

templates/payment/select_gateway.html
{% extends 'payment/base.html' %}
{% load static %}
{% block content %}
<section class="page-section-ptb login-signup parallax"
         style="background: url({% static 'prusta/front/images/login/07.jpg' %});">
    <div class="container">
        <div class="row no-gutter">
            <div class="row mt-70">
                <div class="col-lg-12 col-md-12">
                    <h4 class="mb-30">Select Gateway </h4>
                </div>
                <div class="col-lg-12 col-md-12">
                    <div class="row">
                        <div class="col-lg-4 col-md-4 mb-60">
                            <a class="btn btn-secondary btn-lg" href="{% url 'payment:paypal_checkout' %}?plan={{plan}}"> PayPal</a>
                        </div>
                        <div class="col-lg-4 col-md-4 mb-60">
                            <a class="btn btn-secondary btn-lg" href="{% url 'payment:stripe_checkout' %}?plan={{plan}}"> Stripe</a>
                        </div>
                        <div class="col-lg-4 col-md-4 mb-60">
                            <a class="btn btn-secondary btn-lg" href="{% url 'payment:paypal_checkout' %}?plan={{plan}}"> GoPay</a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</section>

{% endblock %}
{% block scripts %}
<script>

</script>
{% endblock %}

templates/payment/stripe/checkout.html
{% extends 'payment/base.html' %}
{% load static %}
{% block content %}

<section class="page-section-ptb login-signup parallax" >
    <div class="container">
            <div class="row mt-70">
                <div class="col-lg-12 col-md-12 mx-auto text-center">
                    <h4 class="mb-30 ">Redirecting now</h4>
                </div>
            </div>

    </div>
</section>

{% endblock %}
{% block scripts %}
<script src="https://js.stripe.com/v3/"></script>
<script>
$(document).ready(function() {
    json = {"publicKey": "{{PUBLISHABLE_KEY}}", "basePrice": {{price}}, "currency": "{{currency}}"}
    window.config = json;
        var stripe = Stripe(config.publicKey);
        // Setup event handler to create a Checkout Session on submit

            stripe
              .redirectToCheckout({
                sessionId: "{{session_id}}"
              })
              .then(handleResult);
});
</script>
{% endblock %}

templates/payment/success.html
{% extends 'payment/base.html' %}
{% load static %}
{% block content %}
<section class="page-section-ptb login-signup parallax"
         style="background: url();">
    <div class="container">
            <div class="row mt-70">
                <div class="col-lg-12 col-md-12 mx-auto text-center">
                    <h4 class="mb-30 ">Payment Successful. We will redirect to Dashboard now.. </h4>
                </div>
            </div>

    </div>
</section>

{% endblock %}
{% block scripts %}
<script>
$(document).ready(function() {
    var delay = 1000;
    var URL = '/dashboard';
    setTimeout(function(){ window.location = URL; }, delay);
});
</script>
{% endblock %}